# Generated by Django 5.0.3 on 2024-03-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="network",
            old_name="name",
            new_name="location",
        ),
        migrations.AlterField(
            model_name="network",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
