# Generated by Django 5.0.3 on 2024-03-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_name_network_location_alter_network_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="current_load",
        ),
    ]
