# Generated by Django 5.0.3 on 2024-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_item_current_load"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="charge_point_id",
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
